## 주차면수

In [1]:
import pandas as pd
import numpy as np

### 노상주차장

In [14]:
df = pd.read_csv('노상주차장_221212.csv', encoding='utf-8')
df

,일련번호(no),주차장고유값(pl_id),지번주차장이름(pl_nm),구코드(sgg_code),법정동코드(bemd_code),산구분(land_registered),공유주차장구분(shared_parkinglot),번지(beonji),호(ho),주소(지번)(lot_num_address),...,할인정책-다자녀가정(세자녀)(pl_discount_3children),할인정책-국가유공자(pl_discount_person_merit),할인정책-10부제참여차량(pl_discount_ten_part_system),할인정책-요일제차량(pl_discount_weekdayly),할인정책-기타할인율(pl_discount_other_percent),할인정책-기타대상(pl_discount_other_target),그룹관리번호(managing_group_no),경도(longitude),위도(latitude),구축기준일(final_end_dt)
0,1,4758432,249-6 노상주차장,11215,10300,임야도 등록,NaN,249,6,서울특별시 광진구 구의동 249-6 드림-스페이스,...,0,0,0,0,0,0,1121510300030,127.077648,37.555295,2022-11-25
1,2,4735321,16-81 노상주차장,11215,10700,임야도 등록,NaN,16,81,서울특별시 광진구 화양동 16-81,...,0,0,0,0,0,0,1121510700005,127.069443,37.544867,2022-11-25
2,3,4756802,16-93 노상주차장,11215,10700,임야도 등록,NaN,16,93,서울특별시 광진구 화양동 16-93,...,0,0,0,0,0,0,1121510700005,127.069553,37.544947,2022-11-25
3,4,4838021,16-35 노상주차장,11215,10700,임야도 등록,NaN,16,35,서울특별시 광진구 화양동 16-35,...,0,0,0,0,0,0,1121510700005,127.069842,37.545087,2022-11-25
4,5,4736667,32-12 거주자우선주차장,11215,10700,임야도 등록,NaN,32,12,서울특별시 광진구 화양동 32-12,...,0,0,0,0,0,0,1121510700006,127.067637,37.546392,2022-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2525,2526,5544300,송림기사식당길A노상공영주차장,11215,10500,임야도 등록,NaN,227,1,서울특별시 광진구 자양동 227-1,...,50,80,0,0,0,0,1121510500029,127.076742,37.536322,2022-11-25
2526,2527,5544301,송림기사식당길A노상공영주차장,11215,10500,임야도 등록,NaN,227,1,서울특별시 광진구 자양동 227-1,...,50,80,0,0,0,0,1121510500029,127.076764,37.536365,2022-11-25
2527,2528,5547887,596-7 노상주차장,11215,10500,임야도 등록,NaN,596,7,서울특별시 광진구 자양동 596-7,...,0,0,0,0,0,0,1121510500057,127.078734,37.530932,2022-11-25
2528,2529,5547888,다성시티빌앞주차장,11215,10500,임야도 등록,NaN,595,8,서울특별시 광진구 자양동 595-8,...,0,0,0,0,0,0,1121510500048,127.078542,37.530415,2022-11-25
2529,2530,5548085,601-15 노상주차장,11215,10500,임야도 등록,NaN,601,15,서울특별시 광진구 자양동 601-15,...,0,0,0,0,0,0,1121510500041,127.076432,37.532366,2022-11-25

In [15]:
df.columns

Index(['일련번호(no)', '주차장고유값(pl_id)', '지번주차장이름(pl_nm)', '구코드(sgg_code)',
       '법정동코드(bemd_code)', '산구분(land_registered)',
       '공유주차장구분(shared_parkinglot)', '번지(beonji)', '호(ho)',
       '주소(지번)(lot_num_address)', '새주소-도로명(road_nm_address)',
       '새주소-건물번호(bld_num)', '소유주체(possessor)', '급지(pl_grade)', '유무료(pl_fee)',
       '평일시작시간(pl_weekday_start_time)', '평일종료시간(pl_weekday_end_time)',
       '토요일시작시간(pl_sat_start_time)', '토요일종료시간(pl_sat_end_time)',
       '공휴일시작시간(pl_holiday_start_time)', '공휴일종료시간(pl_holiday_end_time)',
       '기본단위시간(pl_basic_rate_min)', '기본단위금액(pl_basic_rate_amt)',
       '추가단위시간(pl_addi_rate_min)', '추가단위금액(pl_addi_rate_amt)',
       '1일(전일)금액(pl_allday_pass_amt)', '1월(정기권)금액(pl_month_pass_amt)',
       '주차요금지불방식(pl_payment_option)', '부제시행(bool_not_driving_system)',
       '운영방식(operation_type)', '구간번호(section)', '구획번호(parcel)',
       '거주자-주간(월)금액(resident_day_month_amt)',
       '거주자-야간(월)금액(resident_night_month_amt)',
       '거주자-전일(월)금액(resident_allday_month_amt)',
       '거주자-평일시작시간(resident_weekday_start_time)',
       '거주자-평일종료시간(resident_weekday_end_time)',
       '거주자-토요일시작시간(resident_sat_start_time)',
       '거주자-토요일종료시간(resident_sat_end_time)',
       '거주자-휴일시작시간(resident_holiday_start_time)',
       '거주자-휴일종료시간(resident_holiday_end_time)',
       '할인정책-장애인(pl_discount_disabled)', '할인정책-경차(pl_discount_compact)',
       '할인정책-다자녀가정(두자녀)(pl_discount_2children)',
       '할인정책-다자녀가정(세자녀)(pl_discount_3children)',
       '할인정책-국가유공자(pl_discount_person_merit)',
       '할인정책-10부제참여차량(pl_discount_ten_part_system)',
       '할인정책-요일제차량(pl_discount_weekdayly)',
       '할인정책-기타할인율(pl_discount_other_percent)',
       '할인정책-기타대상(pl_discount_other_target)', '그룹관리번호(managing_group_no)',
       '경도(longitude)', '위도(latitude)', '구축기준일(final_end_dt)'],
      dtype='object')

In [17]:
data = df.loc[:,['주소(지번)(lot_num_address)']]
data

          주소(지번)(lot_num_address)
0     서울특별시 광진구 구의동 249-6 드림-스페이스
1             서울특별시 광진구 화양동 16-81
2             서울특별시 광진구 화양동 16-93
3             서울특별시 광진구 화양동 16-35
4             서울특별시 광진구 화양동 32-12
...                           ...
2525          서울특별시 광진구 자양동 227-1
2526          서울특별시 광진구 자양동 227-1
2527          서울특별시 광진구 자양동 596-7
2528          서울특별시 광진구 자양동 595-8
2529         서울특별시 광진구 자양동 601-15

[2530 rows x 1 columns]

In [18]:
dong1 = "중곡동"
dong2 = "군자동"
dong3 = "능동"
dong4 = "구의동"
dong5 = "광장동"
dong6 = "화양동"
dong7 = "자양동"

dong1_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong1, na = False)]
dong2_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong2, na = False)]
dong3_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong3, na = False)]
dong4_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong4, na = False)]
dong5_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong5, na = False)]
dong6_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong6, na = False)]
dong7_1 = df[df['주소(지번)(lot_num_address)'].str.contains(dong7, na = False)]
print(len(dong1_1))
print(len(dong2_1))
print(len(dong3_1))
print(len(dong4_1))
print(len(dong5_1))
print(len(dong6_1))
print(len(dong7_1))

672
47
162
328
188
153
845

### 노외주차장

In [20]:
df1 = pd.read_csv('노외주차장_221213.csv', encoding='utf-8')
df1

,일련번호(no),주차장고유값(pl_id),주차장이름(pl_nm),구코드(sgg_code),법정동코드(bemd_code),산구분(land_registered),번지(beonji),호(ho),주소(지번)(lot_num_address),새주소-도로명(road_nm_address),...,전용주차구획-나눔카(pl_num_shared_car),첨두시-주간-시작시간(pl_peak_day_start),첨두시-주간-종료시간(pl_peak_day_end),첨두시-주간-대수(pl_peak_day_num),첨두시-야간-시작시간(pl_peak_night_start),첨두시-야간-종료시간(pl_peak_night_end),첨두시-야간-대수(pl_peak_night_num),경도(longitude),위도(latitude),최종작성일(final_end_dt)
0,1.0,4847399.0,중곡2동주차장,11215.0,10100.0,임야도 등록,133.0,10.0,서울특별시 광진구 중곡동 133-10,도로명주소없음,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.084000,37.556402,2022-11-25
1,2.0,4847403.0,새오름,11215.0,10100.0,임야도 등록,143.0,70.0,서울특별시 광진구 중곡동 143-70,용마산로8마길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.090848,37.561311,2022-11-25
2,3.0,4847409.0,중곡4동주차장,11215.0,10100.0,임야도 등록,87.0,14.0,서울특별시 광진구 중곡동 87-14,영화사로5길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.091839,37.557057,2022-11-25
3,4.0,4847412.0,용마산남측거주자주차장,11215.0,10100.0,임야도 등록,69.0,2.0,서울특별시 광진구 중곡동 69-2,용마산로8길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.092091,37.559210,2022-11-25
4,5.0,4847415.0,중곡3동주민센터,11215.0,10100.0,임야도 등록,684.0,11.0,서울특별시 광진구 중곡동 684,동일로76가길,...,0.0,0.0,0.0,NaN,0.0,0.0,NaN,127.079924,37.568681,2022-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
dong1 = "중곡동"
dong2 = "군자동"
dong3 = "능동"
dong4 = "구의동"
dong5 = "광장동"
dong6 = "화양동"
dong7 = "자양동"

dong1_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong1, na = False)]
dong2_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong2, na = False)]
dong3_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong3, na = False)]
dong4_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong4, na = False)]
dong5_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong5, na = False)]
dong6_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong6, na = False)]
dong7_1 = df1[df1['주소(지번)(lot_num_address)'].str.contains(dong7, na = False)]
print(len(dong1_1))
print(len(dong2_1))
print(len(dong3_1))
print(len(dong4_1))
print(len(dong5_1))
print(len(dong6_1))
print(len(dong7_1))

16
5
4
11
2
5
19

### 부설주차장

In [22]:
df2 = pd.read_csv('부설주차장_221212.csv', encoding='utf-8')
df2

,일련번호(no),주차장고유값(pl_id),주차장이름(pl_nm),구코드(sgg_code),법정동코드(bemd_code),산구분(land_registered),번지(beonji),호(ho),주소(지번)(lot_num_address),새주소-도로명(road_nm_address),...,공휴일개방여부(open_holiday),첨두시-주간-시작시간(pl_peak_day_start),첨두시-주간-종료시간(pl_peak_day_end),첨두시-주간-대수(pl_peak_day_num),첨두시-야간-시작시간(pl_peak_night_start),첨두시-야간-종료시간(pl_peak_night_end),첨두시-야간-대수(pl_peak_night_num),경도(logitude),위도(latitude),최종작성일(final_end_dt)
0,1,4272844,능동로32길 073-00 주차장,11215,10200,임야도 등록,239,20,서울특별시 광진구 능동 239-20,능동로32길,...,미개방,0,0,NaN,0,0,NaN,127.082462,37.554053,2022-11-25
1,2,4272868,M캐슬 가을 주차장,11215,10200,임야도 등록,240,8,서울특별시 광진구 능동 240-8,천호대로114길,...,미개방,0,0,NaN,0,0,NaN,127.081944,37.553433,2022-11-25
2,3,4272953,능동로32길 106-05 주차장,11215,10200,임야도 등록,243,23,서울특별시 광진구 능동 243-23,능동로32길,...,미개방,0,0,NaN,0,0,NaN,127.083952,37.553057,2022-11-25
3,4,4273230,에스에치빌 주차장,11215,10200,임야도 등록,254,28,서울특별시 광진구 능동 254-28 에스에치빌,천호대로120길,...,미개방,0,0,NaN,0,0,NaN,127.086620,37.553290,2022-11-25
4,5,4849415,어린이대공원 구의문,11215,10200,임야도 등록,18,14,서울특별시 광진구 능동 18-14,능동로,...,미개방,0,0,NaN,0,0,NaN,127.085488,37.542811,2022-11-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15815,15816,5127545,대성예가 주차장,11215,10100,임야도 등록,110,5,서울특별시 광진구 중곡동 110-5,자양로53길,...,미개방,0,0,NaN,0,0,NaN,127.092491,37.554612,2022-11-25
15816,15817,5528613,자양로51길 030-05 주차장,11215,10100,임야도 등록,110,29,서울특별시 광진구 중곡동 110-29,자양로51길,...,미개방,0,0,NaN,0,0,NaN,127.092247,37.554447,2022-11-25
15817,15818,5528734,천호대로127길 038-00 주차장,11215,10100,임야도 등록,112,10,서울특별시 광진구 중곡동 112-10,천호대로127길,...,미개방,0,0,NaN,0,0,NaN,127.090747,37.554151,2022-11-25
15818,15819,5528839,자양로45길 079-00 주차장,11215,10100,임야도 등록,94,18,서울특별시 광진구 중곡동 94-18,자양로45길,...,미개방,0,0,NaN,0,0,NaN,127.089799,37.554584,2022-11-25
15819,15820,5057209,면목로17길 005-00 주차장,11215,10100,임야도 등록,210,19,서울특별시 광진구 중곡동 210-19,면목로17길,...,미개방,0,0,NaN,0,0,NaN,127.081448,37.573186,2022-11-25

In [23]:
dong1 = "중곡동"
dong2 = "군자동"
dong3 = "능동"
dong4 = "구의동"
dong5 = "광장동"
dong6 = "화양동"
dong7 = "자양동"

dong1_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong1, na = False)]
dong2_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong2, na = False)]
dong3_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong3, na = False)]
dong4_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong4, na = False)]
dong5_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong5, na = False)]
dong6_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong6, na = False)]
dong7_1 = df2[df2['주소(지번)(lot_num_address)'].str.contains(dong7, na = False)]
print(len(dong1_1))
print(len(dong2_1))
print(len(dong3_1))
print(len(dong4_1))
print(len(dong5_1))
print(len(dong6_1))
print(len(dong7_1))

5541
1074
824
3375
336
1138
3535

### 법정동별 주차면수

In [26]:
dong = ['중곡동', '군자동', '능동', '구의동', '광장동', '화양동', '자양동']
on_street_parkinglot = [672, 47, 162, 328, 188, 153, 845]
off_street_parkinglot = [16, 5, 4, 11, 2, 5, 19]
affiliated_parkinglot = [5541, 1074, 824, 3375, 336, 1138, 3535]

DF = pd.DataFrame(dong, columns=['법정동'])
DF['노상주차장'] = on_street_parkinglot
DF['노외주차장'] = off_street_parkinglot
DF['부설주차장'] = affiliated_parkinglot

DF

   법정동  노상주차장  노외주차장  부설주차장
0  중곡동    672     16   5541
1  군자동     47      5   1074
2   능동    162      4    824
3  구의동    328     11   3375
4  광장동    188      2    336
5  화양동    153      5   1138
6  자양동    845     19   3535

In [28]:
DF['총 주차면수'] = DF['노상주차장'] + DF['노외주차장'] + DF['부설주차장']

DF

   법정동  노상주차장  노외주차장  부설주차장  총 주차면수
0  중곡동    672     16   5541    6229
1  군자동     47      5   1074    1126
2   능동    162      4    824     990
3  구의동    328     11   3375    3714
4  광장동    188      2    336     526
5  화양동    153      5   1138    1296
6  자양동    845     19   3535    4399

In [29]:
DF.to_csv('법정동별_주차면수.csv', index=False, encoding='cp949')

In [31]:
Df = pd.read_csv('법정동별_주차면수.csv',  encoding='cp949')
Df

   법정동  노상주차장  노외주차장  부설주차장  총 주차면수
0  중곡동    672     16   5541    6229
1  군자동     47      5   1074    1126
2   능동    162      4    824     990
3  구의동    328     11   3375    3714
4  광장동    188      2    336     526
5  화양동    153      5   1138    1296
6  자양동    845     19   3535    4399